config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  
  resources :quotes

  root 'quotes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/quote.rb
class Quote < ApplicationRecord
    validates :text, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
    def index
        @quotes = Quote.all.order('created_at DESC')
    end

    def new
        @quote = Quote.new
    end

    def create
        @quote = Quote.new(quote_params)

        if @quote.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    private
    def quote_params
        params.require(:quote).permit(:text)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quoteo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/quotes/index.html.erb
<div class="header">
    quoteo
</div>
<div class="wrapper">
    <%= link_to '+', new_quote_path %>
</div>
<div class="center">
    
    <% @quotes.each do |quote| %>
      <p>
        "<%= quote.text %>"
      </p>
    <% end %>
</div>

app/views/quotes/new.html.erb
<div class="header">
    quoteo
</div>

<div class="center">
  <h1>New quote</h1>

  <%= form_with scope: :quote, url: quotes_path, local: true do |form| %>
    <p>
      <%= form.text_area :text %>
    </p>
  
    <p>
      <%= form.submit %>
    </p>
  <% end %>
  <% if @quote.errors.any? %>
      <div id="error_explanation">
          <% @quote.errors.full_messages.each do |msg| %>
            <%= msg %>
          <% end %>
      </div>
    <% end %>
</div>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>